tasks:
  - init: |
      pushd etl/
      pip install pre-commit && pip install detect-secrets
      pip install -r requirements.txt && pip install -r requirements-dev.txt
      popd

      pushd etl/
      pre-commit install
      touch .env
      aws s3 cp s3://mongulu-files/enrich_cache.sqlite enrich_cache.sqlite
      curl "https://media.interieur.gouv.fr/rna/rna_waldec_20220301.zip" -o rna_waldec_20220301.zip
      unzip rna_waldec_20220301.zip -d rna_waldec_20220301
      rm -f rna_waldec_20220301.zip
      jupyter trust filter-cameroon.ipynb && jupyter trust enrich-database.ipynb
      popd
    command: |
      bash .envrc.gitpod
      cp .envrc.gitpod .envrc
      jupyter lab --ServerApp.allow_origin=\'$(gp url 8888)\'

ports:
- port: 8888
  onOpen: open-browser

vscode:
  extensions:
    - vivaxy.vscode-conventional-commits
