tasks:
  - init: |
      sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform
        
      pushd /tmp
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip && sudo ./aws/install && rm awscliv2.zip && rm -rf aws/
      popd
      
      pushd /tmp
      curl "https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz" -o spark-3.2.1-bin-hadoop3.2.tgz
      tar -xzf spark-3.2.1-bin-hadoop3.2.tgz
      sudo mv spark-3.2.1-bin-hadoop3.2 /opt/spark-3.2.1
      popd
      
      pushd etl/
      pip install -r requirements.txt && pip install -r requirements-dev.txt
      popd
    command: |
      #python3 -m ipykernel install --user
      #aws configure
      #pushd infra ; terraform init && popd
      cd etl/
      curl "https://media.interieur.gouv.fr/rna/rna_waldec_20220301.zip" -o rna_waldec_20220301.zip
      unzip rna_waldec_20220301.zip -d rna_waldec_20220301
      rm -f rna_waldec_20220301.zip
      jupyter notebook --NotebookApp.allow_origin=\'$(gp url 8888)\'

ports:
- port: 8888
  onOpen: open-browser