tasks:
  - init: |
      pushd etl/
      pip3.10 install pre-commit && pip3.10 install detect-secrets
      pip3.10 install -r requirements.txt && pip3.10 install -r requirements-dev.txt
      popd

      pushd etl/
      pre-commit install
      pre-commit install --hook-type commit-msg
      aws s3 cp s3://mongulu-files/enrich_cache.sqlite enrich_cache.sqlite
      curl "https://media.interieur.gouv.fr/rna/rna_waldec_20220301.zip" -o rna_waldec_20220301.zip
      unzip rna_waldec_20220301.zip -d rna_waldec_20220301
      rm -f rna_waldec_20220301.zip
      popd
    command: |
      bash .envrc.gitpod
      cp .envrc.gitpod .envrc

vscode:
  extensions:
    - vivaxy.vscode-conventional-commits
    - sourcegraph.cody-ai
    - donjayamanne.githistory
    - amazonwebservices.aws-toolkit-vscode
