tasks:
  - init: |
      sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform
      
      npm install commitizen -g
      commitizen init cz-conventional-changelog --save-dev --save-exact
      npm install --save-dev @commitlint/prompt @commitlint/config-conventional commitizen
      touch .git/hooks/prepare-commit-msg
      echo "exec < /dev/tty && node_modules/.bin/cz --hook || true" >> .git/hooks/prepare-commit-msg
        
      pushd /tmp
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip && sudo ./aws/install && rm awscliv2.zip && rm -rf aws/
      popd
      
      pushd /tmp
      curl "https://dlcdn.apache.org/spark/spark-3.2.2/spark-3.2.2-bin-hadoop3.2.tgz" -o spark-3.2.2-bin-hadoop3.2.tgz
      tar -xzf spark-3.2.2-bin-hadoop3.2.tgz
      sudo mv spark-3.2.2-bin-hadoop3.2 /opt/spark-3.2.2
      popd
      
      pushd etl/
      pip install pre-commit && pip install detect-secrets
      pip install -r requirements.txt && pip install -r requirements-dev.txt
      popd
    command: |
      aws configure
      cd etl/
      pre-commit install
      touch .env
      aws s3 cp s3://mongulu-files/enrich_cache.sqlite enrich_cache.sqlite
      curl "https://media.interieur.gouv.fr/rna/rna_waldec_20220301.zip" -o rna_waldec_20220301.zip
      unzip rna_waldec_20220301.zip -d rna_waldec_20220301
      rm -f rna_waldec_20220301.zip
      jupyter trust filter-cameroon.ipynb && jupyter trust enrich-database.ipynb
      jupyter lab --ServerApp.allow_origin=\'$(gp url 8888)\'

ports:
- port: 8888
  onOpen: open-browser

vscode:
  extensions:
    - vivaxy.vscode-conventional-commits