name: Test Workflow
on: [pull_request, push, workflow_dispatch]

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1.2.1
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
